# Generated by Django 3.1.4 on 2020-12-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
    ]
