# Generated by Django 3.1.4 on 2020-12-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20201224_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='header',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Заголовок'),
        ),
    ]
