# Generated by Django 2.2.6 on 2021-01-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0019_auto_20210114_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='header',
        ),
    ]
