# Generated by Django 2.2.6 on 2021-01-19 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0024_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
